spring:
  datasource:
    url: jdbc:h2:./gmwdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: edwyn1!
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html